# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Project', verbose_name='project'),
        ),
    ]
