# Generated by Django 3.0.4 on 2020-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200330_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='youtube_published',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='youtube_published_tags',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='youtube_status',
            field=models.SmallIntegerField(choices=[(1, 'Waiting'), (2, 'Encoding'), (3, 'Tagging'), (4, 'Sending')], editable=False, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='youtube_tags',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='youtube_task',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
