# Generated by Django 3.0.4 on 2020-04-01 13:17

import archive.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20200401_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='youtube_file',
            field=models.FileField(editable=False, null=True, storage=archive.utils.OverwriteStorage(), upload_to='archive/final'),
        ),
    ]
