# Generated by Django 3.0.4 on 2020-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_audiobook_youtube_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
