# Generated by Django 3.0.4 on 2020-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_audiobook_youtube_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='piece')),
                ('is_outro', models.BooleanField(default=False)),
                ('min_audiobook_duration', models.IntegerField(default=0)),
            ],
        ),
    ]
