# Generated by Django 3.0.4 on 2020-05-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='youtube_file',
        ),
    ]
