# Generated by Django 3.0.6 on 2020-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_populate_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='slug',
            field=models.SlugField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
