# Generated by Django 3.0.6 on 2020-05-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_url_to_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='url',
        ),
    ]
