# Generated by Django 3.0.6 on 2020-05-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_remove_audiobook_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='parts_count',
        ),
    ]
