# Generated by Django 3.0.6 on 2020-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_remove_audiobook_parts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='youtube_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='youtube_volume',
            field=models.CharField(blank=True, help_text='If set, audiobooks with the save value will be published as single YouTube video.', max_length=1000, verbose_name='Volume name for YouTube'),
        ),
    ]
