# Generated by Django 3.0.6 on 2020-05-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20200529_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='index',
            field=models.IntegerField(default=0, help_text='Ordering of parts of a book.', verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='mp3_status',
            field=models.SmallIntegerField(choices=[(1, 'Queued'), (10, 'Waiting'), (20, 'Encoding'), (30, 'Tagging'), (40, 'Converting audio'), (50, 'Converting video'), (60, 'Assembling audio'), (70, 'Assembling video'), (80, 'Joining audio and video'), (100, 'Sending'), (110, 'Setting thumbnail')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='ogg_status',
            field=models.SmallIntegerField(choices=[(1, 'Queued'), (10, 'Waiting'), (20, 'Encoding'), (30, 'Tagging'), (40, 'Converting audio'), (50, 'Converting video'), (60, 'Assembling audio'), (70, 'Assembling video'), (80, 'Joining audio and video'), (100, 'Sending'), (110, 'Setting thumbnail')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='slug',
            field=models.SlugField(help_text='WL catalogue slug of the book.', max_length=120),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='youtube_status',
            field=models.SmallIntegerField(choices=[(1, 'Queued'), (10, 'Waiting'), (20, 'Encoding'), (30, 'Tagging'), (40, 'Converting audio'), (50, 'Converting video'), (60, 'Assembling audio'), (70, 'Assembling video'), (80, 'Joining audio and video'), (100, 'Sending'), (110, 'Setting thumbnail')], editable=False, null=True),
        ),
    ]
