# Generated by Django 3.0.6 on 2020-06-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20200529_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='youtube_volume',
            field=models.CharField(blank=True, help_text='If set, audiobooks with the save value will be published as single YouTube video.', max_length=100, verbose_name='Volume name for YouTube'),
        ),
    ]
