# Generated by Django 3.1.2 on 2020-10-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_auto_20201022_1414'),
        ('archive', '0018_auto_20200703_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='youtube.youtube'),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='mp3_status',
            field=models.SmallIntegerField(choices=[(5, 'Queued'), (10, 'Waiting'), (20, 'Encoding'), (30, 'Tagging'), (40, 'Converting audio'), (50, 'Converting video'), (60, 'Assembling audio'), (70, 'Assembling video'), (80, 'Joining audio and video'), (100, 'Sending'), (110, 'Setting thumbnail')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='ogg_status',
            field=models.SmallIntegerField(choices=[(5, 'Queued'), (10, 'Waiting'), (20, 'Encoding'), (30, 'Tagging'), (40, 'Converting audio'), (50, 'Converting video'), (60, 'Assembling audio'), (70, 'Assembling video'), (80, 'Joining audio and video'), (100, 'Sending'), (110, 'Setting thumbnail')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='slug',
            field=models.SlugField(blank=True, help_text='WL catalogue slug of the book.', max_length=120),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='youtube_status',
            field=models.SmallIntegerField(choices=[(5, 'Queued'), (10, 'Waiting'), (20, 'Encoding'), (30, 'Tagging'), (40, 'Converting audio'), (50, 'Converting video'), (60, 'Assembling audio'), (70, 'Assembling video'), (80, 'Joining audio and video'), (100, 'Sending'), (110, 'Setting thumbnail')], editable=False, null=True),
        ),
    ]
