# Generated by Django 3.1.2 on 2020-10-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0017_auto_20201022_1535'),
        ('archive', '0019_auto_20201022_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='youtube.youtube'),
        ),
    ]
