# Generated by Django 3.1.2 on 2021-01-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_auto_20201022_1535'),
        ('archive', '0019_auto_20210121_1249'),
    ]

    operations = [
    ]
