# Generated by Django 3.1.2 on 2021-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_merge_20210121_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='archive/project'),
        ),
    ]
