# Generated by Django 3.1.2 on 2021-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_auto_20210316_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='info_flac',
            field=models.FileField(blank=True, upload_to='archive/info_flac'),
        ),
    ]
