# Generated by Django 3.1.14 on 2021-12-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_create_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.config'),
        ),
    ]
