# Generated by Django 3.1.14 on 2022-10-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_auto_20211222_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='mp3_published_tags',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='mp3_tags',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='mp3_task',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='ogg_published_tags',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='ogg_tags',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='ogg_task',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='youtube_published_tags',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='youtube_tags',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='youtube_task',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='license_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary', to='archive.license', verbose_name='license'),
        ),
    ]
