# Generated by Django 3.1.14 on 2022-10-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0027_auto_20221025_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_sell',
            field=models.BooleanField(default=True, verbose_name='Do sprzedaży'),
        ),
        migrations.AddField(
            model_name='project',
            name='private_notes',
            field=models.TextField(blank=True, verbose_name='Prywatne notatki'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archive.license', verbose_name='Wymagana licencja'),
        ),
    ]
