# Generated by Django 3.1.14 on 2022-10-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0028_auto_20221025_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='license_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary', to='archive.license', verbose_name='secondary license'),
        ),
    ]
