# Generated by Django 3.0.4 on 2020-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_secrets', models.TextField(blank=True)),
                ('oauth2_storage', models.TextField(blank=True, editable=False)),
                ('title_template', models.CharField(blank=True, max_length=1024)),
                ('description_template', models.TextField(blank=True)),
                ('category', models.IntegerField(null=True)),
                ('intro_card', models.FileField(blank=True, upload_to='')),
                ('intro_card_length', models.FloatField(null=True)),
                ('card', models.FileField(blank=True, upload_to='')),
                ('loop_video', models.FileField(blank=True, upload_to='')),
                ('outro_card', models.FileField(blank=True, upload_to='')),
                ('outro_card_length', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'YouTube configuration',
                'verbose_name_plural': 'YouTube configurations',
            },
        ),
    ]
