# Generated by Django 3.0.4 on 2020-03-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200330_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube',
            old_name='intro_card_length',
            new_name='intro_card_duration',
        ),
        migrations.RenameField(
            model_name='youtube',
            old_name='outro_card_length',
            new_name='outro_card_duration',
        ),
    ]
