# Generated by Django 3.0.4 on 2020-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20200331_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='client_secrets',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='oauth2_storage',
        ),
        migrations.AddField(
            model_name='youtube',
            name='genres',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='youtube',
            name='thumbnail_template',
            field=models.FileField(blank=True, upload_to='youtube/thumbnail'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='card',
            field=models.FileField(blank=True, upload_to='youtube/card'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='intro_card',
            field=models.FileField(blank=True, upload_to='youtube/intro_card'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='loop_video',
            field=models.FileField(blank=True, upload_to='youtube/loop_video'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='outro_card',
            field=models.FileField(blank=True, upload_to='youtube/outro_card'),
        ),
    ]
