# Generated by Django 3.0.4 on 2020-05-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_move_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='intro_card',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='intro_card_duration',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='outro_card',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='outro_card_duration',
        ),
    ]
