# Generated by Django 3.0.4 on 2020-05-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='intro_flac',
            field=models.FileField(blank=True, upload_to='youtube/intro_flac'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='outro_flac',
            field=models.FileField(blank=True, upload_to='youtube/outro_flac'),
        ),
    ]
