# Generated by Django 3.0.4 on 2020-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_auto_20200518_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'public'), ('unlisted', 'unlisted'), ('private', 'private')], default='unlisted', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtube',
            name='category',
            field=models.IntegerField(blank=True, choices=[(27, 'Edukacja')], null=True),
        ),
    ]
