# Generated by Django 3.0.6 on 2020-07-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_auto_20200520_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('is_active', models.BooleanField()),
                ('background', models.FileField(upload_to='youtube/thumbnail')),
                ('definition', models.TextField()),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('collections', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
