# Generated by Django 3.0.6 on 2020-07-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_auto_20200706_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailtemplate',
            name='authors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thumbnailtemplate',
            name='epochs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='thumbnailtemplate',
            name='kinds',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
