# Generated by Django 3.1.2 on 2020-10-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_auto_20200706_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailtemplate',
            name='youtube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.youtube'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='name',
            field=models.CharField(default='Wolne Lektury', max_length=255),
            preserve_default=False,
        ),
    ]
